name: mytorch-gpu
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - cupy=14.2.*
  - cuda-version=13.2
  - numpy>=2.0,<2.5
  - pillow
  - pip
  - setuptools
  - wheel
  - python-build
  - twine
  - pytest
  - pytest-cov
  - ruff
